[tool.poetry]
name = "freeflow"
version = "0.1.0"
description = "Freeflow agent"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{ include = "featureflow" }]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
